### ISSUE TITLE
"Unsupported data type" error after load_index

### ISSUE THREAD

**Issue by seanmacavaney** [BlaiseMuhirwa/flatnav-experimental#73]
Thanks for the great package!

In the Python bindings, it looks like `_data_type` isn't being set when `load_index` is called. This means that invocations of `cast_and_call` from the search methods always fail.

Steps to reproduce:

```python
>>> import flatnav
>>> index = flatnav.index.IndexIPFloat.load_index('/path/to/index')
>>> index.search(queries=queries, ef_search=100, K=10)
ValueError: Unsupported data type.
```

**Comment by BlaiseMuhirwa** [comment]
Thanks for pointing this out. We will push a fix very soon!

**Comment by seanmacavaney** [comment]
Awesome, thanks! I suspect the fix will involve some templating magic. But I've got a not-so-elegant temporary fix here, in case that's helpful: https://github.com/seanmacavaney/flatnav/commit/a1dd7f68b61c685069ccedf995e6ca91f30782db

**Comment by BlaiseMuhirwa** [comment]
I think this is good enough for now. Do you want to submit a pull request for this? I think the longer-term solution will be to serialize one byte for the data type when we invoke `index.save()` so that on index loading we can infer what data type to use.

**Comment by seanmacavaney** [comment]
Sure thing, on it.
